name: Generate README

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - name: Generate README
        run: |
          deno run --allow-read=. ./generate_index.ts > ./README.md
      - name: Commit changes
        run: |
          if git diff --quiet ./README.md; then
            echo "No changes"
            exit 0
          fi
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./README.md
          git commit -m "docs: Auto-generate README.md"
          git push origin main 
