env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-unused-vars:
    - error
    - vars: all
      args: all
      argsIgnorePattern: "^_"
      ignoreRestSiblings: false
settings:
  react:
    version: detect
